In [1]:
docs = ['go pakistan',
		'pakistan pakistan',
		'hip hip hurray',
		]

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [3]:
tokenizer.fit_on_texts(docs)


In [7]:
len(tokenizer.word_index)

5

In [10]:
tokenizer.word_index

{'<nothing>': 1, 'pakistan': 2, 'hip': 3, 'go': 4, 'hurray': 5}

In [4]:
import numpy as np
sequences = tokenizer.texts_to_sequences(docs)
sequences #= np.array(sequences)

[[4, 2], [2, 2], [3, 3, 5]]

In [5]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[4, 2, 0],
       [2, 2, 0],
       [3, 3, 5]], dtype=int32)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(6,output_dim=3,input_length=5))
#model.build(input_shape=5)
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 347ms/step
[[[ 0.03910568 -0.04930151  0.03494776]
  [ 0.02569571 -0.00441799  0.01448879]
  [ 0.00377005  0.0033712   0.00498651]]

 [[ 0.02569571 -0.00441799  0.01448879]
  [ 0.02569571 -0.00441799  0.01448879]
  [ 0.00377005  0.0033712   0.00498651]]

 [[-0.00511779  0.04720355  0.0002059 ]
  [-0.00511779  0.04720355  0.0002059 ]
  [ 0.0163268   0.04972589 -0.03248018]]]
