In [21]:
docs = ['go pakistan',
		'pakistan pakistan',
		'hip hip hurray',
		'jeetega bhai jeetega pakisatn jeetega',
		'pakistan zinda bad',
		'babar babar',
		'sachin sachin',
		'afridi afrid',
		'pakistan ki jeet hogi',
		'inquilab zindabad']

In [22]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [23]:
tokenizer.fit_on_texts(docs)

In [9]:
tokenizer.word_index

{'<nothing>': 1,
 'pakistan': 2,
 'jeetega': 3,
 'hip': 4,
 'babar': 5,
 'sachin': 6,
 'go': 7,
 'hurray': 8,
 'bhai': 9,
 'pakisatn': 10,
 'zinda': 11,
 'bad': 12,
 'afridi': 13,
 'afrid': 14,
 'ki': 15,
 'jeet': 16,
 'hogi': 17,
 'inquilab': 18,
 'zindabad': 19}

In [24]:
import numpy as np
sequences = tokenizer.texts_to_sequences(docs)
sequences #= np.array(sequences)

[[7, 2],
 [2, 2],
 [4, 4, 8],
 [3, 9, 3, 10, 3],
 [2, 11, 12],
 [5, 5],
 [6, 6],
 [13, 14],
 [2, 15, 16, 17],
 [18, 19]]

In [25]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 7,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4,  8,  0,  0],
       [ 3,  9,  3, 10,  3],
       [ 2, 11, 12,  0,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [13, 14,  0,  0,  0],
       [ 2, 15, 16, 17,  0],
       [18, 19,  0,  0,  0]], dtype=int32)

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(20,output_dim=3,input_length=5))
model.build(input_shape=5)
model.summary()

Model: "sequential_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_15 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [51]:
model.compile('adam','accuracy')

In [52]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step
[[[ 0.02530071 -0.01165972  0.03652592]
  [-0.00158135 -0.01619508  0.03406096]
  [ 0.01460761  0.04914807 -0.04148227]
  [ 0.01460761  0.04914807 -0.04148227]
  [ 0.01460761  0.04914807 -0.04148227]]

 [[-0.00158135 -0.01619508  0.03406096]
  [-0.00158135 -0.01619508  0.03406096]
  [ 0.01460761  0.04914807 -0.04148227]
  [ 0.01460761  0.04914807 -0.04148227]
  [ 0.01460761  0.04914807 -0.04148227]]

 [[-0.01256878  0.02990434  0.00306913]
  [-0.01256878  0.02990434  0.00306913]
  [-0.03739774  0.02278555  0.04201258]
  [ 0.01460761  0.04914807 -0.04148227]
  [ 0.01460761  0.04914807 -0.04148227]]

 [[ 0.0265263   0.00176535 -0.00011713]
  [ 0.00228866 -0.00095304 -0.04379861]
  [ 0.0265263   0.00176535 -0.00011713]
  [-0.01047703  0.0028554  -0.00810301]
  [ 0.0265263   0.00176535 -0.00011713]]

 [[-0.00158135 -0.01619508  0.03406096]
  [-0.00586393  0.02707293  0.01566917]
  [ 0.02970581  0.00893798 -0.0401076 ]
  [ 0.01460761  0.04914807 -0.041

In [25]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [21]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [22]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [ ]:

X_train[1]

array([ 8255,     5, 25249,   656,   245,  2350,     5,     4,  9837,
         131,   152,   491,    18, 46151,    32,  7464,  1212,    14,
           9,     6,   371,    78,    22,   625,    64,  1382,     9,
           8,   168,   145,    23,     4,  1690,    15,    16,     4,
        1355,     5,    28,     6,    52,   154,   462,    33,    89,
          78,   285,    16,   145,    95], dtype=int32)

In [34]:


model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()


Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_5 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5


InvalidArgumentError: Graph execution error:

Detected at node sequential_9_1/embedding_8_1/GatherV2 defined at (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ipykernel_launcher.py", line 18, in <module>

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\traitlets\config\application.py", line 1075, in launch_instance

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ipykernel\kernelapp.py", line 739, in start

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\tornado\platform\asyncio.py", line 211, in start

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ipykernel\kernelbase.py", line 534, in process_one

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ipykernel\ipkernel.py", line 362, in execute_request

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ipykernel\kernelbase.py", line 778, in execute_request

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ipykernel\ipkernel.py", line 449, in do_execute

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ipykernel\zmqshell.py", line 549, in run_cell

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py", line 3077, in run_cell

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py", line 3132, in _run_cell

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py", line 3336, in run_cell_async

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py", line 3519, in run_ast_nodes

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py", line 3579, in run_code

  File "C:\Users\user\AppData\Local\Temp\ipykernel_6900\863240012.py", line 2, in <module>

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 377, in fit

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 220, in function

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 133, in multi_step_on_iterator

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 114, in one_step_on_data

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 58, in train_step

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\layer.py", line 936, in __call__

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\ops\operation.py", line 58, in __call__

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\models\sequential.py", line 220, in call

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\models\functional.py", line 183, in call

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\ops\function.py", line 177, in _run_through_graph

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\models\functional.py", line 648, in call

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\layer.py", line 936, in __call__

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\ops\operation.py", line 58, in __call__

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\embedding.py", line 150, in call

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\ops\numpy.py", line 5581, in take

  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend\tensorflow\numpy.py", line 2274, in take

indices[0,1] = 32462 is not in [0, 30000)
	 [[{{node sequential_9_1/embedding_8_1/GatherV2}}]] [Op:__inference_multi_step_on_iterator_4990]